//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadEmail.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataLoaderConfig
    {
        public string location { get; set; }
        public string archieveLocation { get; set; }
        public Nullable<int> refreshRateInSeconds { get; set; }
        public Nullable<int> batchSizeInRows { get; set; }
    }
}
