//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadEmail.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailData
    {
        public int id { get; set; }
        public string fromEmailId { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public string orginalFileName { get; set; }
        public string newFileName { get; set; }
        public byte[] timeRead { get; set; }
    }
}
